/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : Time,
});
export const MoodEntry = IDL.Record({
  'userId' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'emoji' : IDL.Text,
  'timestamp' : Time,
  'moodScore' : IDL.Nat,
});
export const UserStats = IDL.Record({
  'badges' : IDL.Vec(IDL.Text),
  'currentStreak' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponse,
});

export const idlService = IDL.Service({
  'addJournalEntry' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addMoodEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getLatestMoodEntry' : IDL.Func([IDL.Text], [IDL.Opt(MoodEntry)], ['query']),
  'getMoodEntries' : IDL.Func([IDL.Text], [IDL.Vec(MoodEntry)], ['query']),
  'getUserStats' : IDL.Func([IDL.Text], [UserStats], ['query']),
  'sendChatMessage' : IDL.Func(
      [IDL.Vec(ChatMessage), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'transformResponse' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : Time,
  });
  const MoodEntry = IDL.Record({
    'userId' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'emoji' : IDL.Text,
    'timestamp' : Time,
    'moodScore' : IDL.Nat,
  });
  const UserStats = IDL.Record({
    'badges' : IDL.Vec(IDL.Text),
    'currentStreak' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponse,
  });
  
  return IDL.Service({
    'addJournalEntry' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addMoodEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getLatestMoodEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MoodEntry)],
        ['query'],
      ),
    'getMoodEntries' : IDL.Func([IDL.Text], [IDL.Vec(MoodEntry)], ['query']),
    'getUserStats' : IDL.Func([IDL.Text], [UserStats], ['query']),
    'sendChatMessage' : IDL.Func(
        [IDL.Vec(ChatMessage), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'transformResponse' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };