/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage { 'content' : string, 'role' : string }
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface JournalEntry {
  'id' : string,
  'content' : string,
  'userId' : string,
  'timestamp' : Time,
}
export interface MoodEntry {
  'userId' : string,
  'note' : [] | [string],
  'emoji' : string,
  'timestamp' : Time,
  'moodScore' : bigint,
}
export type Time = bigint;
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponse,
}
export interface UserStats {
  'badges' : Array<string>,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'addJournalEntry' : ActorMethod<[string], string>,
  'addMoodEntry' : ActorMethod<
    [string, bigint, string, [] | [string]],
    undefined
  >,
  'getDailyQuote' : ActorMethod<[], string>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getLatestMoodEntry' : ActorMethod<[string], [] | [MoodEntry]>,
  'getMoodEntries' : ActorMethod<[string], Array<MoodEntry>>,
  'getUserStats' : ActorMethod<[string], UserStats>,
  'sendChatMessage' : ActorMethod<[Array<ChatMessage>, [] | [string]], string>,
  'transformResponse' : ActorMethod<[TransformArgs], HttpResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];